
// This file is automatically generated by Clarigen.
// Don't make changes to this file, or they'll
// be overwritten.
import { factory } from "https://deno.land/x/clarigen@v0.4.16/mod.ts";
import { simnet } from "./clarigen-contracts.ts";

export const { test, contracts, accounts } = factory(simnet);

export const {
  clarityBitcoin,
  ordyswapV1
} = contracts;
